spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bluemoon8126
    password: qeadzc9898!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required:
          auth: true
          connectiontimeout:
          timeout:
          writetimeout: